name: todo CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python (you can specify the Python version you need)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Set up database (using SQLite for simplicity in CI)
      - name: Setup database
        run: |
          python manage.py migrate

      # Step 5: Run tests
      - name: Run tests
        run: |
          python manage.py test

      # Step 6: Collect static files (if needed for the project)
      - name: Collect static files
        run: |
          python manage.py collectstatic --noinput
